### PR TITLE
Render index.html and modify API for attractions. Set host as 0.0.0.0

### PR DESCRIPTION
**Pull request by ann-yachen**
Here are some updates for this branch:

Set host as 0.0.0.0

- Set host = 0.0.0.0 in python server

Render index.html and modify API for attractions

- Render index.html based on the design of Figma and show attractions by fetching API
- Pagination with loading more attractions when scrolling to the end of page
- Search function by keyword of attractions, including selecting categories from pop-up menu when clicking search bar
- Modify /api/attractions for pagination by getting the first row of next page

URL for reference

- http://35.155.30.220:3000/

Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Category block should hide after we click one of them.
2. Layout is broken in small to middle size devices. (360px ~ 1200px)
3 115 107 58_3000_(Samsung Galaxy S8+)

**Comment by ann-yachen** [comment]
Sorry for missing some information about the requests.
I have modified them and updated to AWS EC2, please check the details as below:

Modify RWD and the menu with categories for keyword. Add function to sense if fetching completed when pagination

- Modify RWD for screen size between 360px to 1200px
- Add function to close pop-up menu when clicking the categories
- Add function to sense if fetching completed when pagination to avoid calling API too many times

URL for reference

- http://35.155.30.220:3000/

Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Well Done.

**Comment by ann-yachen** [comment]
Thank you.
And sorry for forgetting re-request in the previous comment.

**Pull request merged**
