### PR TITLE
Setup User APIs and Render on Pages for Membership Stsyem

### PR DESCRIPTION
**Pull request by ann-yachen**
Here are some updates for this branch:

Setup User APIs and Render on Pages for Membership Stsyem

- Setup RESTful-APIs and use JWT for membership system including register, get log-in status, log-in and log-out based on MVC-like architecture
- Create features based on MVC-like architecture for membership system at index.html and attraction.html

Optimize Codes for the Previous Features

- Modify Attractions APIs based on MVC-like architecture
- Use Jinja2 template inheritance to render nav and footer

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10
Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Good for this week. But I just notice that line height of attraction description should be larger.
aaa

**Comment by ann-yachen** [comment]
I have modified line-height for attraction description in attaction page.
Please check.

Modify line-height for attraction description

- Modify line-height for attraction description in attaction page

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10
Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

**Review by cwpeng — APPROVED** [review]
Good. Done. :)

**Comment by ann-yachen** [comment]
Thank you.
Have merged :)

**Pull request merged**
