### PR TITLE
Setup Booking System

### PR DESCRIPTION
**Pull request by ann-yachen**
Here are some updates for this branch:

Setup Booking System

- Setup APIs for user booking
- Add feature to allow user for booking a reservation in attraction page
- Render booking.html by fetching API of reservation, add feature for user to delete reservation

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10
- http://35.155.30.220:3000/booking

Please let me know if there is any question.
Many thanks.
Ann (陳璵安)

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by cwpeng** [comment]
Remember to merge pull request first before doing another task.

**Comment by ann-yachen** [comment]
Thank you for reminding.
Will merge in advance before other commits next time.
Have optimized codes and fixed bugs for the previous commits.
Please let me know if there is any question.

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10
- http://35.155.30.220:3000/booking

Many thanks.
Ann (陳璵安)

**Comment by ann-yachen** [comment]
Have merged to main.
Thank you :)

**Comment by cwpeng** [comment]
OK. :)

**Pull request merged**
