### PR TITLE
Render attraction.html for each attraction. Add links in index.html

### PR DESCRIPTION
**Pull request by ann-yachen**
Here are some updates for this branch:

Render attraction.html for each attraction and add links in index.html

- Render attraction.html for each attraction based on design
- Use fetching to get attracion data from /api/attraction/{id} and render in page
- Add function for user to choose time for guide with different prices
- Add links to each attraction page in index.html
- Add function for images of attraction as carousel

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10

Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but line height of attraction description and transport information should be larger.

**Comment by ann-yachen** [comment]
I have modified CSS for attraction.html for line-height setting and updated to AWS EC2.
Please check the details as below:

Modify CSS for attraction.html

- Modify line-height for attraction description and transport block
- Modify booking form line-height
- Modify space between the top area with images/profile/booking form to the bottom area with description/address/transport

URLs for reference

- http://35.155.30.220:3000/
- http://35.155.30.220:3000/attraction/10

Please let me know if there is any question.

Many thanks.
Ann (陳璵安)

**Review by cwpeng — APPROVED** [review]
Good. Much Better.

You can try to use Flask Blueprint to seperate API routes from app.py

**Comment by ann-yachen** [comment]
Thank you!
Have merged pull request to main.

**Pull request merged**
